// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleClusterOperator) DeepCopyInto(out *SimpleClusterOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleClusterOperator.
func (in *SimpleClusterOperator) DeepCopy() *SimpleClusterOperator {
	if in == nil {
		return nil
	}
	out := new(SimpleClusterOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimpleClusterOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleClusterOperatorList) DeepCopyInto(out *SimpleClusterOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimpleClusterOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleClusterOperatorList.
func (in *SimpleClusterOperatorList) DeepCopy() *SimpleClusterOperatorList {
	if in == nil {
		return nil
	}
	out := new(SimpleClusterOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimpleClusterOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleClusterOperatorSpec) DeepCopyInto(out *SimpleClusterOperatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleClusterOperatorSpec.
func (in *SimpleClusterOperatorSpec) DeepCopy() *SimpleClusterOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(SimpleClusterOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleClusterOperatorStatus) DeepCopyInto(out *SimpleClusterOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleClusterOperatorStatus.
func (in *SimpleClusterOperatorStatus) DeepCopy() *SimpleClusterOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(SimpleClusterOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
