// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperator":       schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperator(ref),
		"github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorSpec":   schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperatorSpec(ref),
		"github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorStatus": schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperatorStatus(ref),
	}
}

func schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperator(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleClusterOperator is the Schema for the simpleclusteroperators API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorSpec", "github.com/openshift/simple-clusteroperator-operator/pkg/apis/simpleclousteroperator/v1alpha1.SimpleClusterOperatorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperatorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleClusterOperatorSpec defines the desired state of SimpleClusterOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_simpleclousteroperator_v1alpha1_SimpleClusterOperatorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SimpleClusterOperatorStatus defines the observed state of SimpleClusterOperator",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
